@echo off
cls
color 40
cls
:error
cls
ECHO COFFEE OS COULDNT BOOT CORRECTLY, THIS IS CAUSED BY NO BOOT CHECK  IN THIS SYSTEM.
ECHO.
ECHO THIS IS FATAL, YOU NEED TO REDOWNLOAD COFFEE OS
ECHO.
ECHO SHUT DOWN THE COMPUTER AND CHECK THE DRIVE NOW!
pause
goto error
